# Generated by Django 3.2.9 on 2021-11-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
    ]
