# Generated by Django 3.2.9 on 2021-12-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20211128_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
